services:
  ums:
    image: universalmediaserver/ums:latest
    container_name: ums
    ports:
      - 9001:9001
      - 5002:5002
      - 1044:1044
    volumes:
      - /storage/media/qbit:/usr/src/ums/media
# Uncomment block below to enable GPU passtrough to container
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: 1
#               capabilities: [gpu]
    restart: unless-stopped
